openapi: "3.1.0"
info:
  title: "gotovomp_server API"
  description: "gotovomp_server API"
  version: "1.0.0"
paths:
  /auth/signIn:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
  /auth/signUp:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                type: "string"
  /ping:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Pong!"
  /user/me:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/User"
  /metrics:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
components:
  schemas:
    SignInRequest:
      type: "object"
      properties:
        usernameOrPhoneNumber:
          type: "string"
        password:
          type: "string"
      required:
        - "usernameOrPhoneNumber"
        - "password"
    AuthResponse:
      type: "object"
      properties:
        token:
          type: "string"
      required:
        - "token"
    SignUpRequest:
      type: "object"
      properties:
        username:
          type: "string"
        firstName:
          type: "string"
        lastName:
          type: "string"
        phoneNumber:
          type: "string"
        password:
          type: "string"
      required:
        - "username"
        - "phoneNumber"
        - "password"
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        username:
          type: "string"
        firstName:
          type: "string"
        lastName:
          type: "string"
        phoneNumber:
          type: "string"
        password:
          type: "string"
      required:
        - "username"
        - "phoneNumber"
        - "password"
