name: Build and Publish Docker Image

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch

env:
  IMAGE_NAME: ghcr.io/pickme-team/gotovomp-server
  IMAGE_TAG: latest

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4  # Specify the Gradle version you want to use

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish Docker Image with Jib
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
        run: |
          gradle jib \
            -Djib.to.image=$IMAGE_NAME:$IMAGE_TAG \
            -Djib.to.auth.username=$GITHUB_USERNAME \
            -Djib.to.auth.password=$GITHUB_TOKEN
